### ISSUE TITLE
Add docker-compose file

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/certstream-server-go#16]

**Comment by Mxrk** [comment]
Fixed with https://github.com/d-Rickyy-b/certstream-server-go/commit/c96f94c4c9fe4ec1f665d1bd7fcc5673c495708e?

**Comment by d-Rickyy-b** [comment]
Implemented in c96f94c4c9fe4ec1f665d1bd7fcc5673c495708e
