### ISSUE TITLE
I have some questions about transparent local deployment of certificates, can you please advise?

### ISSUE THREAD

**Issue by K0zero** [d-Rickyy-b/certstream-server-go#18]
HI bro!
I have some questions about local deployment of [certificate-transparency-go](https://github.com/google/certificate-transparency-go), can you please advise? i think you are the export of this erea.
I wanna do some experiments about certificate-transparency, and i wanna deploy these characters on my school's local net servers :
- one CT Server 
- one CA server
- some domains which use local deployed CA certificate and i wanna see the certificate on the local CT server's CT log

can you give me some adivce?  i have seen the [ct-go repo's manual deployment](https://github.com/google/certificate-transparency-go/blob/master/trillian/docs/ManualDeployment.md) and [CA server repo ](https://github.com/letsencrypt/boulder#development) but i have no idea on how to build them and let them connected.

**Comment by d-Rickyy-b** [comment]
Hi @K0zero and thank you for creating an issue.

Sadly I have never set up my own CT server, nor my own CA. I just created this tool to analyze certificates published to public CT logs. You're probably better off by asking on Reddit or on certain forums. As much as I would like to help you, I don't think I can.

Cheers,
Rico

**Comment by K0zero** [comment]
I appreciate you replying to me 
I will continue to follow this project of yours
