### ISSUE TITLE
Adding sha256 fingerprint

### ISSUE THREAD

**Issue by deterri** [d-Rickyy-b/certstream-server-go#19]
Thanks for this awesome project. I had the same internal dialogue when it came to running the CaliDog Elixir server vs what you've built here - and what you've built is way better than what I could've done in Go.

How much trouble would it be to add a sha256 fingerprint in addition to the sha1 fingerprint you're doing? I'd be happy to try and implement.

**Comment by d-Rickyy-b** [comment]
Hi there and thank you for creating this issue. Happy you found this project helpful!

I created a Pull request for this feature. Will do some more tests before I merge it. Feel free to check it out and give feedback on it.

Cheers,
Rico
