### ISSUE TITLE
Docker instructions need fixing

### ISSUE THREAD

**Issue by gcleaves** [d-Rickyy-b/certstream-server-go#21]
Hi. The example Docker run command needs fixing. It should be something like this:

`docker run -d -v /path/to/config.yml:/app/config.yml -p 8080:8080 0rickyy0/certstream-server-go`

And the config.yml must be edited to change one of the server ports, otherwise an error is thrown about an occupied port.

Thanks for publishing this code, the standard certstream endpoint is flaky.

**Comment by d-Rickyy-b** [comment]
Thank you. I addressed both mentioned issues and drafted a new release [v1.3.1](https://github.com/d-Rickyy-b/certstream-server-go/releases/tag/v1.3.1).
