### ISSUE TITLE
ARM tagged docker image

### ISSUE THREAD

**Issue by kick707** [d-Rickyy-b/certstream-server-go#27]
HI, first so excited to see and use this project! working amazing on my Mac intel but oi need ARM image to run it on cloud hosting which is an ARM64, I saw you have compiled binaries for ARM, can you add ARM64 tagged image to docker-hub so I will need to modify only my docker-compose file ? Please. ?

**Comment by d-Rickyy-b** [comment]
Hi, I am running an instance of certstream-server-go on an ARM server but not via docker. I will check and add a docker image for ARM as well.

**Comment by kick707** [comment]
Appreciate that ! thank you !!!

**Comment by d-Rickyy-b** [comment]
I implemented multi arch docker builds and am now also pushing the image to the [github container registry](https://github.com/d-Rickyy-b/certstream-server-go/pkgs/container/certstream-server-go). Starting with the next release there will be arm docker images 🎉 .

Implemented in: https://github.com/d-Rickyy-b/certstream-server-go/compare/109e8d6...93e3a243

**Comment by kick707** [comment]
Ricky !!!! Amazing work !!!!! Thank you very much !!!!
